-- Should be done manually in the database
-- CREATE USER medusa_user WITH PASSWORD 'your_secure_password';

CREATE SCHEMA medusa;

GRANT USAGE ON SCHEMA medusa TO medusa_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA medusa TO medusa_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA medusa TO medusa_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA medusa 
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO medusa_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA medusa 
GRANT USAGE, SELECT ON SEQUENCES TO medusa_user;
